pipeline {
    agent any

    stages {
        stage('Deploy') {
            steps {
                sshagent(credentials: ['deploy-ssh-gcp']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no vitya199909@34.53.12.23 "
                      cd /home/vitya199909/ProvedCode/App_Docker_Compose/frontend/provedcode-frontend-vitya199909 &&
                      git pull &&
                      cd /home/vitya199909/ProvedCode/App_Docker_Compose/backend/provedcode-backend-vitya199909 &&
                      git pull &&
                      cd /home/vitya199909/ProvedCode/App_Docker_Compose &&
                      docker compose down &&
                      docker compose up -d --build
                    "
                    '''
                }
            }
        }
    }
}
