Vagrant.configure("2") do |config|
  # ---------------------------
  # Frontend VM
  # ---------------------------
  config.vm.define "frontend" do |frontend|
    frontend.vm.box = "ubuntu/focal64"
    frontend.vm.hostname = "frontend"
    frontend.vm.network "private_network", ip: "192.168.56.10"
    config.vm.synced_folder "./provedcode-frontend-vitya199909", "/home/vagrant/frontend", type: "rsync"
    frontend.vm.provision "shell", privileged: true, path: "provision-frontend.sh"
    frontend.vm.network "forwarded_port", guest: 3000, host: 3000
  end

  # ---------------------------
  # Database VM
  # ---------------------------
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.12"
    db.vm.provision "shell", path: "provision-db.sh"
    db.vm.network "forwarded_port", guest: 5432, host: 5432
  end

  # ---------------------------
  # Backend VM
  # ---------------------------
  config.vm.define "backend" do |backend|
    backend.vm.box = "ubuntu/focal64"
    backend.vm.hostname = "backend"
    backend.vm.network "private_network", ip: "192.168.56.11"
    backend.vm.synced_folder "./provedcode-backend-vitya199909", "/home/vagrant/backend", type: "rsync"
    backend.vm.provision "shell", privileged: true, path: "provision-backend.sh"
    backend.vm.network "forwarded_port", guest: 8080, host: 8080
  end
end